spring.application.name=ExpenseTrackerJava
#database url
spring.datasource.url=
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
#db connection login info
spring.datasource.username=
spring.datasource.password=
